kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: sealed-secrets

# Include the base Sealed Secrets manifests.
bases:
  - ../../base

# the sealed secret controller supports updating the status:
# field of sealedsecrets starting with version 0.12.0
# upstream changed the default to off with release 0.12.1 because of bugs
# see https://github.com/bitnami-labs/sealed-secrets/blob/main/RELEASE-NOTES.md
# for more info.
# with 0.17.0 this is no longer required, update-status becomes the default
# as of 2021/11/18 0.17.0 is released but artifacts are missing.
patchesJson6902:
- target:
    version: v1
    group: apps
    kind: Deployment
    name: sealed-secrets-controller
    namespace: sealed-secrets
  path: patch-update-status.yaml
