apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
  name: test
  namespace: application-gitops
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: 'test-*'
    server: '*'
  sourceRepos:
  - '*'
