kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: sealed-secrets

resources:
  - ../../base
  - ../anyuid
  # update status is not required with version >= 0.17
  # - ../update-status
