kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../default
  - test-project.yaml
  - test-group.yaml
  - production-project.yaml
  - production-group.yaml

patches:
  - path: rbac-patch.yaml
