kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base/

patches:
  - patch: |-
      - op: add
        path: /spec/dex/openShiftOAuth
        value: true
    target:
      kind: ArgoCD
      name: application-gitops
