apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    # argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: '4'
  labels:
    gitops.ownedBy: cluster-config
  name: mtc-operator
spec:
  destination:
    namespace: open-cluster-management
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: components/apps/migration-toolkit-for-containers/operator/overlays/release-v1.6
    repoURL: https://github.com/rhatservices/openshift-gitops.git
    targetRevision: main
  syncPolicy:
    # automated:
    #   selfHeal: true
